### ISSUE TITLE
Given groups=1, weight of size [32, 5, 3, 9], expected input[4, 2, 36, 512] to have 5 channels, but got 2 channels instead

### ISSUE THREAD

**Issue by runningtosun** [hujinsen/awesome-pytorch-StarGAN-VC#11]
looking forward your reply

**Comment by lvxiaoqi** [comment]
需要训练4个样本，你只用了2个

**Comment by sainishalini** [comment]
Hi there, another error for 6 speakers, preprocess.py runs fine but main.py throwing an error as below:
input = module(input)
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main(config)
  File "main.py", line 34, in main
    solver.train()
  File "/Users/shalinisaini/pytorch-StarGAN-VCtk-oct-6small/solver.py", line 169, in train
    out_r = self.D(x_real, label_org)
  File "/Users/shalinisaini/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/shalinisaini/pytorch-StarGAN-VCtk-oct-6small/model.py", line 115, in forward
    x = self.d1(x)
  File "/Users/shalinisaini/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/shalinisaini/pytorch-StarGAN-VCtk-oct-6small/model.py", line 20, in forward
    x1 = self.c1(x)
  File "/Users/shalinisaini/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/shalinisaini/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/Users/shalinisaini/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size [32, 5, 3, 9], expected input[6, 7, 36, 512] to have 5 channels, but got 7 channels instead

any help is appreciated to work in the right direction.

thanks for your help!
