### ISSUE TITLE
No files present  when I run main.py

### ISSUE THREAD

**Issue by Husnain08** [hujinsen/awesome-pytorch-StarGAN-VC#4]
When I run main.py, I get the following error. Can you tell what is possibly wrong?
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    main(config)
  File "main.py", line 35, in main
    solver.train()
  File "C:\Users\user pc\PycharmProjects\pygan\solver.py", line 126, in train
    norm = Normalizer()
  File "C:\Users\user pc\PycharmProjects\pygan\utility.py", line 47, in __init__
    self.norm_dict = self.normalizer_dict()
  File "C:\Users\user pc\PycharmProjects\pygan\utility.py", line 77, in normalizer_dict
    raise Exception('====no match files!====')
Exception: ====no match files!====

**Comment by KujouAika** [comment]
I met the same problem. Looking forward to any answer

**Comment by lvxiaoqi** [comment]
原因是windows下面glob.glob(p) 获取文件路径时正斜杠"/"被转义了的反双斜杠替代了"\\",在CommonInfo类的speakers方法里面把双斜杠"\\"替换成正斜杠"/"就可以了。
